language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ "$CC" = "gcc" ]; then export CC=gcc-4.8 CXX=g++-4.8 PKG=g++-4.8; fi
  - if [ "$CC" = "gcc" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CC" = "gcc" ]; then sudo apt-get -qq update; fi
  - sudo apt-get install -qq cmake valgrind $PKG
  - $CC --version

before_script:
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DLIBNODE_USE_THREAD=ON -DLIBNODE_BUILD_TEST=ON -DLIBNODE_BUILD_EXT=ON -DLIBNODE_BUILD_EXAMPLE=ON ..
  - make
  - gtest/libnode-test
  - valgrind --leak-check=full gtest/libnode-test
